id: P008047
initial_creation_type: ocr
source_metadata:
  id: bdr:W1PD159415
  title: སྐད་གསུམ་ཚིག་མཛོད་གསར་པ།（དབྱིན། བོད། རྒྱ།）
  author: ''
  volumes:
    3daffcec5db147bd8110c2497c264b75:
      image_group_id: I4PD4150
      title: ''
      volume_number: 1
      total_pages: 1522
ebook_metadata:
  title: སྐད་གསུམ་ཚིག་མཛོད་གསར་པ།（དབྱིན། བོད། རྒྱ།）
  author: ''
  sku: P008047
  cover: cover.jpg
  layers:
  - pagination
