id: I83826798
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T06:48:34+00:00'
last_modified: '2022-06-08T18:03:16.756557+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD159415
  title: སྐད་གསུམ་ཚིག་མཛོད་གསར་པ།（དབྱིན། བོད། རྒྱ།）
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    C636:
      image_group_id: I4PD4150
      title: Volume 1 of skad gsum tshig mdzod gsar pa/（dbyin/ bod/ rgya/）
      total_pages: 1522
      order: 1
      base_file: C636.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
